### ISSUE TITLE
Accessibility regarding requirement of servo spline gear

### ISSUE THREAD

**Issue by SnowGliderr** [reubenstr/zuko#1]
The servo spline gear (25T internal, 12T external) used in this design is patented as seen in 
servocity.com/2305-series-brass-mod-0-8-servo-gear-25-tooth-spline-12-tooth. This significantly impacts its availability compared to the other parts of Zuko, that can mostly be sourced from a multitude of manufacturers or substituted with similar parts, despite being a relatively simple hardware component. For example, the more commonly used 20mm metal disc servo horn is available from many sites internationally for just a few dollars (or just a couple in some areas) for all 12. On the other hand, the servo spline gear appears to be almost non-existent outside of specialty stores, and even the relatively cheap Aliexpress link provided in the BOM puts them at about the cost the cost of about 2 high torque servos for the 12 pieces required. As such, it would be great if Zuko could officially be compatible with metal disc servo horns, or if the use of the spline gears were reduced. At least for the hip servos, it should be possible to use metal discs by lengthening the chassis slightly and widening a few holes.

P.S. Thanks for the great contributions in porting OpenQuad code to ROS 2 and a Kangal-style chassis.

**Comment by reubenstr** [comment]
Completely agree on all points. With this, I am reworking all joints to accept a more commonly available servo horn. The following image/URLs are to a horn that has enough shaft length to allow the upper leg joint to retain the ability to support the lower leg's linking bridge' press bearing needed for smooth motion:
![servo-horn-in-test](https://user-images.githubusercontent.com/16118193/153312525-5e200081-97c3-4dee-a49e-e292de4568ce.png)
https://www.amazon.com/gp/product/B09JLLWDW2
https://www.aliexpress.com/item/1005001513123335.html

Here are screenshots of the upper leg rework and the hip  preliminary reworked joints: 

![horn-on-bridge](https://user-images.githubusercontent.com/16118193/153312419-cf2aaa84-7727-46af-a1de-9d6b1062cc4f.png)
![horn-on-upper-leg](https://user-images.githubusercontent.com/16118193/153312421-677964c8-8a75-4574-8266-abab3678ba39.png)
![horn-on-upper-leg-cross-section](https://user-images.githubusercontent.com/16118193/153312418-57f4183b-9377-43c2-b1a2-593ec6667c4d.png)

So far I don't foresee any diminished aesthetics or reduced mechanical rigidity. There is slightly added difficulty in printing the hip module, but should be negligible.

Thanks for the feedback! I will close the issue after test prints work out. Please let me know your opinion of this solution.

.

**Comment by SnowGliderr** [comment]
This looks like an elegant solution for the hips and upper legs, and the horns are easier to source. Seems like the rod end links will need to be shifted outwards to accommodate the thickness of the horn for the lower leg servo.

**Comment by reubenstr** [comment]
Redesign complete.

An adapter was created for the lower leg drive horn to keep the linkages as close to the driving servo as the original design.

![zuko-robot-dog-leg-linkages](https://user-images.githubusercontent.com/16118193/153733590-10b6947b-b2fe-4700-b16f-50e25e8551f8.png)

Printed parts are working well, likely minor tweaks for the press fit of the leg bearing as I begin to assemble the new parts.
